name: Secret Scanning on Code Changes

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main

jobs:
  secret-scanning-review:
    name: Secret Scanning Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Secret Scanning Review Action
        uses: advanced-security/secret-scanning-review-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-alert: false           # Set true to fail workflow on secret detection
          fail-on-alert-exclude-closed: false
          runtime: python                # or 'powershell'
