name: Secret Scanning Review

on:
  pull_request:

jobs:
  secret-scanning-review:
    runs-on: ubuntu-latest
    steps:
      - name: Secret Scanning Review Action
        uses: advanced-security/secret-scanning-review-action@v1
        with:
          token: ${{ secrets.SECRET_SCAN_REVIEW_GITHUB_TOKEN }}
          fail-on-alert: true                  # Fail the workflow if secrets are found
          fail-on-alert-exclude-closed: true  # Ignore alerts that have been closed
          runtime: 'python'                    # Or 'powershell' depending on your environment
