name: Secret Scanning Review

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main

jobs:
  secret-scanning-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Secret Scanning Review Action
        uses: advanced-security/secret-scanning-review-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-alert: false               # Do not fail the workflow, just report alerts
          fail-on-alert-exclude-closed: true
          runtime: 'python'                  # or 'powershell'
